### ISSUE TITLE
Can't build with master branch 040dc15

### ISSUE THREAD

**Issue by codingspirit** [aws/amazon-freertos-ble-android-sdk#23]
**Describe the bug**
In newest commit 040dc15061def61495128dc7bf30d6903bcafe5c on master branch:

https://github.com/aws/amazon-freertos-ble-android-sdk/blob/040dc15061def61495128dc7bf30d6903bcafe5c/app/src/main/java/software/amazon/freertos/demo/DeviceScanFragment.java#L134

`BLE_INITIALIZED` is not part of `AmazonFreeRTOSConstants.BleConnectionState` in release 1.1.0/1.0.0.

Do we have any plan to update build.gradle file for app?

https://github.com/aws/amazon-freertos-ble-android-sdk/blob/040dc15061def61495128dc7bf30d6903bcafe5c/app/build.gradle#L22

Or  we have to roll back until next release is ready?

**Build info**
SDK commit id: 040dc15061def61495128dc7bf30d6903bcafe5c

**System info**
API 29

**To Reproduce**
Clone repository and build the demo app

**Comment by ravibhagavandas** [comment]
Hi,
We are working on a new release for the SDK. Meantime could you choose to pull demo from the commit version for the release 1.1.0 which is `6cd9f86a21d32b40345baef224acd9dc0ac4d276`. You can also use option 2 as mentioned in the README to pull the latest master branch commit of SDK.

**Comment by codingspirit** [comment]
Hi,

Thanks, We understand that check out to specific commit do help for passing the build but it's a little bit tricky workaround for users who are following [BLE DEMO DOC](https://docs.aws.amazon.com/freertos/latest/userguide/ble-demo.html).

So shall I close this issue? Or close it after 1.2.0 is released?

**Comment by ravibhagavandas** [comment]
@codingspirit 

You can keep this post open for reference until the new release is out.

**Comment by ravibhagavandas** [comment]
I have released a new version of SDK 1.2.0 and updated the demo app to use the new SDK as the dependency.
