### ISSUE TITLE
Unable to access gatt characterstice

### ISSUE THREAD

**Issue by purvagevaria** [aws/amazon-freertos-ble-android-sdk#25]
I want to add callback or indication of service discovery and all. Right now there is no way in sdk in which I can trigger now discover service this services are discovered perform this operation write or notify custom characteristics. 
How to enable those ?

**Comment by ravibhagavandas** [comment]
Hi,

Right now those callbacks are not exposed to the demo directly from the SDK, but you can always browse through code starting from here to see how callbacks are invoked at different stages:
https://github.com/aws/amazon-freertos-ble-android-sdk/blob/master/amazonfreertossdk/src/main/java/software/amazon/freertos/amazonfreertossdk/AmazonFreeRTOSDevice.java#L444

**Comment by purvagevaria** [comment]
Yes I checked that but using this app is there any way to get those call backs ?

**Comment by ravibhagavandas** [comment]
This replied to in the other post #26

**Comment by purvagevaria** [comment]
My issue got resovled after using sdk as module
