### ISSUE TITLE
Unable to customise gatt characteristics operation

### ISSUE THREAD

**Issue by purvagevaria** [aws/amazon-freertos-ble-android-sdk#26]
Hi ,
I am developing an application and using this freetos sdk for it. I want to apply some security features before sending the data over cloud. And for that I need to apply some customized code before sending the data .
But for that I need some call back on app side about characteristics scan or read or modify in app side.  So how to perfrom any code in gatt profile ?

**Comment by ravibhagavandas** [comment]
@purvagevaria 

For a demo on creating a custom GATT service and sending data over to cloud, you can take a look at the GATT server demo: https://docs.aws.amazon.com/freertos/latest/userguide/ble-demo.html#ble-demo-server
But please note that currently the GATT client part of the demo is only supported on IOS SDK. For android SDK you can closely look into how the MQTT proxy GATT service is implemented here: https://github.com/aws/amazon-freertos-ble-android-sdk/blob/master/amazonfreertossdk/src/main/java/software/amazon/freertos/amazonfreertossdk/AmazonFreeRTOSDevice.java#L833

**Comment by purvagevaria** [comment]
I want to get call backs and modification on gatt services but unfortunately I am not able to receive any call backs on app side about gatt characteristics change or received.

**Comment by ravibhagavandas** [comment]
Hi,

The callbacks for GATT characteristic read/write is implemented within [BluetoothGattCallback ](https://github.com/aws/amazon-freertos-ble-android-sdk/blob/master/amazonfreertossdk/src/main/java/software/amazon/freertos/amazonfreertossdk/AmazonFreeRTOSDevice.java#L441) object. For adding custom gatt service and characteristics you can add the service and characteristic uuid constants in this [file](https://github.com/aws/amazon-freertos-ble-android-sdk/blob/6eee4a24b1e35ae775376f419cc416f00db26fa2/amazonfreertossdk/src/main/java/software/amazon/freertos/amazonfreertossdk/AmazonFreeRTOSConstants.java) and then implement the corresponding UUID handling logic of yours in `onCharacteristicRead`,  `onCharacteristicWrite` , `onCharacteristicChanged` methods. For processing descriptor written notifications you can write your implementation for `onDescriptorWrite` method.

**Comment by purvagevaria** [comment]
Imported sdk as a module and now I can edit code and customise chars
