### ISSUE TITLE
Network connection closes on any incoming messages from Cloud

### ISSUE THREAD

**Issue by ChristyBrouwer** [aws/amazon-freertos-ble-android-sdk#38]
**Describe the bug**
Any time a message is published via AWS IoT on a topic which the system is subscribed to, an error occurs and the connection gets closed. The system's code works entirely in combination with the IOS SDK, it purely gives the error when connected to the cloud via the Android SDK.

**Build info**
ESP runs the master freertos branch, commit [12d7ad7](https://github.com/aws/amazon-freertos/commit/12d7ad76b19fe97e601cb6b7c58bf50f5f11d630)
Android SDK runs the master branch, commit [de66e51](https://github.com/aws/amazon-freertos-ble-android-sdk/commit/de66e51cdeaab196eee27db04e0a5a35986c942b)

**System info**
Android 10
Bluetooth 5.0, Bluetooth LE/Smart/4.0+
ESP32 DevKitC 32D

**To Reproduce**
Issue happens any time a message is sent from the Cloud to a topic the ESP is subscribed to

**Log**
Log from ESP:
```
38 18621 [ble] [ERROR] [MQTT_BLE] [iot_ble_mqtt_transport.c:1173] 39 18621 [ble] An error occured when receiving data from the channel. No data was recorded.40 18621 [ble]
41 18871 [ble] [ERROR][MQTT][18871] (MQTT connection 0x3ffdc2bc) Unknown packet type ff received.
42 18871 [ble] [ERROR][MQTT][18871] (MQTT connection 0x3ffdc2bc) Error processing incoming data. Closing connection.
43 18872 [ble] [INFO ][MQTT][18871] (MQTT connection 0x3ffdc2bc) Network connection closed.

```

**Comment by lundinc2** [comment]
Hi @ChristyBrouwer,

Thank you for this report, we will investigate this.

Thanks,

Carl

**Comment by dachalco** [comment]
Hi @ChristyBrouwer 

Thanks for bringing this to our attention. It highlighted a legitimate bug which I fixed in the above PR.
Can you please pull these updates then see if your issue persists?

**Comment by ChristyBrouwer** [comment]
Hi @dachalco 

Thank you for working out a possible solution! I've tried pulling the updates to see if the issue persists but I've ran into a new one regarding freertos so I can't test the SDK yet. I made an issue for it on the freertos github, [#2901](https://github.com/aws/amazon-freertos/issues/2901). I will let you know if the original problem is fixed when that is solved!
