### ISSUE TITLE
Does not  build Task 'wrapper' not found in project ':app'.

### ISSUE THREAD

**Issue by rwainstei** [aws/amazon-freertos-ble-android-sdk#39]
getting this 
Task 'wrapper' not found in project ':app'. 
Any idea ?

**Comment by ravibhagavandas** [comment]
Could you provide more information on the error, along with error logs.

 What version and the commit ID of the SDK are you using?

**Comment by alfred2g** [comment]
Closing issue, please @rwainstei reopen if you have more questions

**Comment by m1dnight** [comment]
The instructions on building the android app are unclear if you are not experienced with mobile development. The readme instructs to execute `./gradlew installDebug`, but that is not defined in the gradle.build file. 

I managed to get the gradle wrapper installed, but I don't know which Gradle version is required, or which JDK is necessary.
