### ISSUE TITLE
cannot open wifi provisioning

### ISSUE THREAD

**Issue by haziqharuka** [aws/amazon-freertos-ble-android-sdk#42]
hye, im new to this and i have face problem where i open WiFi provisioning. 
I already connect the esp32 with my device but i cannot do the WiFi provisioning. when i try to open WiFi provisioning it just blank page. Can someone help me.

**Comment by paulbartell** [comment]
@haziqharuka Could you give us a little more information about what you have tried and any debugging logs?

**Comment by sukhmanm** [comment]
Hi @haziqharuka, were you able to make any progress on this?

**Comment by yourslab** [comment]
Since there has been no update on this issue for a while, I will be closing it but please feel free to open another issue if you are still facing problems.
