### ISSUE TITLE
Require a button to refresh the wifi AP list

### ISSUE THREAD

**Issue by lylezhu2014** [aws/amazon-freertos-ble-android-sdk#43]
**Describe the bug**
There is an issue that no all surrounding wifi APs are listed in network setting UI. Require a button to request the wifi provisioning example to rescan surrounding WIFI APs.
Please refer to the following picture,
[
![WeChat Image_20210623114436](https://user-images.githubusercontent.com/7939450/123032404-77413d80-d418-11eb-8f37-22b932ad5a9d.jpg)
](url)

**Comment by dan4thewin** [comment]
Thanks, @lylezhu2014 .  I've mentioned this to one of my peers, and you may expect him to respond.  We ask for your patience, as there are many demands on his time right now.

**Comment by ravibhagavandas** [comment]
Hi @lylezhu2014 

Thanks for reporting this. I acknowledge that this is a useful feature in the demo. We will add this into our queue for prioritization. Meanwhile to unblock yourself you can try adding an additional button to WiFi provisioning fragment [here](https://github.com/aws/amazon-freertos-ble-android-sdk/blob/master/app/src/main/java/software/amazon/freertos/demo/WifiProvisionFragment.java#L39) and call `listNetworks()` API as part of button click action.

**Comment by kstribrnAmzn** [comment]
Going to close this out as this library is now deprecated
