### ISSUE TITLE
Older Android versions don't work with BLE Provisioning, Demo & Firmware

### ISSUE THREAD

**Issue by rrivadeneira-rsc** [aws/amazon-freertos-ble-android-sdk#5]
**Describe the bug**
We have tried to use the demo app and the AFR 1.4.7 and 1.5 BLE provisioning demos unsuccessfully with older phones such as Android 6.0 (used by a vast majority of Android users). We are not able to connect to the device via BLE. It seems that we get kicked out of the connection immediately, and we are not able to discover any services. On the device side, we are using an ESP32.

**Build info**
**What is the branch and commit on the device side?** previous suggested commit from the ble-beta, _17ba347f for AFR 1.4.7_, and I believe _5a201aca for AFR 1.5_ 
**What is the branch and tag the SDK side?** latest commit from the /beta branch tag v0.9.4
**Does pulling the latest code help resolve the issue?** No

**To Reproduce**
**What is the frequency of this issue?** Every time we try to establish a BLE connection
**Steps to reproduce the behavior:** Load the app on an older Android phone (we tried with a 6.0) and try to connect to a device

**Log**
Could you provide log on both the device side and SDK side?
**DEVICE (ESP32) LOG:**
```
2079 6157097 [Btc_task] [INFO ][DEMO][61570970] BLE Connected to remote device, connId = 0

E (61572781) BT_SMP: pairing failed - slave requires auth is 0xd but peer auth is 0x5 local auth is 0xd

W (61572791) BT_L2CAP: L2CA_EnableUpdateBleConnParams - unknown BD_ADDR 000000000000

W (61572871) BT_BTM: btm_sec_clr_temp_auth_service() - no dev CB

E (61572871) BT_BTM: Device not found

W (61572871) BT_APPL: BTA got unregistered event id 31

W (61572881) BT_APPL: BTA got unregistered event id 31

2080 6157285 [Btc_task] [INFO ][DEMO][61572850] BLE disconnected with remote device, connId = 0
```

**MOBILE APP DEMO LOG:**
```
05-31 10:00:11.491 19583-19583/software.amazon.freertos.demo D/AmazonFreeRTOSManager: Found ble device: 24:0A:C4:1D:78:AE RSSI: -59

05-31 10:00:13.681 19583-19583/software.amazon.freertos.demo D/ViewRootImpl: ViewPostImeInputStage processPointer 0

05-31 10:00:13.811 19583-19583/software.amazon.freertos.demo D/ViewRootImpl: ViewPostImeInputStage processPointer 1

05-31 10:00:13.811 19583-19583/software.amazon.freertos.demo I/DeviceScanFragment: connect switch isChecked: ON

05-31 10:00:13.821 19583-19583/software.amazon.freertos.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.amazonaws.mobile.client.AWSMobileClient$10>

05-31 10:00:13.821 19583-19583/software.amazon.freertos.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.amazonaws.mobile.client.AWSMobileClient$10>

05-31 10:00:13.831 19583-19583/software.amazon.freertos.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.amazonaws.mobile.client.AWSMobileClient$3>

05-31 10:00:13.831 19583-19583/software.amazon.freertos.demo I/art: Rejecting re-init on previously-failed class java.lang.Class<com.amazonaws.mobile.client.AWSMobileClient$3>

05-31 10:00:13.921 19583-19583/software.amazon.freertos.demo D/BluetoothGatt: connect() - device: 24:0A:C4:1D:78:AE, auto: true

05-31 10:00:13.921 19583-19583/software.amazon.freertos.demo D/BluetoothGatt: registerApp()

05-31 10:00:13.921 19583-19583/software.amazon.freertos.demo D/BluetoothGatt: registerApp() - UUID=001c5cff-940f-400d-b060-6f1ae591bb27

05-31 10:00:13.961 19583-19598/software.amazon.freertos.demo D/BluetoothGatt: onClientRegistered() - status=0 clientIf=10

05-31 10:00:13.991 19583-19595/software.amazon.freertos.demo D/BluetoothGatt: onAutoConnectionStatusCb()status =0

05-31 10:00:15.121 19583-19695/software.amazon.freertos.demo I/AmazonFreeRTOSManager: Stopping ble device scan

05-31 10:00:15.121 19583-19695/software.amazon.freertos.demo D/BluetoothAdapter: STATE_ON

05-31 10:00:15.121 19583-19695/software.amazon.freertos.demo D/BluetoothAdapter: STATE_ON

05-31 10:00:15.121 19583-19695/software.amazon.freertos.demo D/BluetoothLeScanner: Stop Scan

05-31 10:00:17.671 19583-19595/software.amazon.freertos.demo D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=10 device=24:0A:C4:1D:78:AE

05-31 10:00:17.681 19583-19595/software.amazon.freertos.demo I/FRD: BLE connection state changed: 0; new state: BLE_CONNECTED

05-31 10:00:17.711 19583-19595/software.amazon.freertos.demo I/FRD: Connected to GATT server.

05-31 10:00:17.721 19583-19595/software.amazon.freertos.demo D/FRD: Processing BLE command: DISCOVER_SERVICES remaining mqtt queue 0, network queue 0

05-31 10:00:17.721 19583-19595/software.amazon.freertos.demo D/BluetoothGatt: discoverServices() - device: 24:0A:C4:1D:78:AE

05-31 10:00:17.741 19583-19595/software.amazon.freertos.demo D/BluetoothGatt: onClientConnParamsChanged() - Device=24:0A:C4:1D:78:AE interval=6 status=0

05-31 10:00:17.741 19583-19595/software.amazon.freertos.demo D/BluetoothGatt: onClientConnParamsChanged() - Device=24:0A:C4:1D:78:AE interval=39 status=0

05-31 10:00:17.791 19583-19583/software.amazon.freertos.demo D/FRD: Bond state changed from 10 to 11

05-31 10:00:17.791 19583-19598/software.amazon.freertos.demo D/BluetoothGatt: onSearchComplete() = Device=24:0A:C4:1D:78:AE Status=0

05-31 10:00:17.791 19583-19598/software.amazon.freertos.demo I/FRD: Discovered Ble gatt services successfully. Bonding state: 11

05-31 10:00:17.791 19583-19598/software.amazon.freertos.demo D/FRD: GattService: 00001801-0000-1000-8000-00805f9b34fb

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 00002a05-0000-1000-8000-00805f9b34fb

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD: GattService: 00001800-0000-1000-8000-00805f9b34fb

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 00002a00-0000-1000-8000-00805f9b34fb

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 00002a01-0000-1000-8000-00805f9b34fb

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 00002aa6-0000-1000-8000-00805f9b34fb

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD: GattService: 8a7f1168-48af-4efb-83b5-e679f932ff00

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: DEVICE_VERSION

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: IOT_ENDPOINT

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: DEVICE_MTU

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD: GattService: 3113a187-4b9f-4f9a-aa83-c614e11bff00

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 3113a187-4b9f-4f9a-aa83-c614e11bff01

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 3113a187-4b9f-4f9a-aa83-c614e11bff02

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 3113a187-4b9f-4f9a-aa83-c614e11bff03

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: 3113a187-4b9f-4f9a-aa83-c614e11bff04

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD: GattService: a9d7166a-d72e-40a9-a002-48044cc3ff00

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: a9d7166a-d72e-40a9-a002-48044cc3ff01

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: a9d7166a-d72e-40a9-a002-48044cc3ff02

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: a9d7166a-d72e-40a9-a002-48044cc3ff03

05-31 10:00:17.801 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: a9d7166a-d72e-40a9-a002-48044cc3ff04

05-31 10:00:17.811 19583-19598/software.amazon.freertos.demo D/FRD:  |-characteristics: a9d7166a-d72e-40a9-a002-48044cc3ff05

05-31 10:00:17.811 19583-19598/software.amazon.freertos.demo D/FRD: There's no ble command in the queue.

05-31 10:00:18.161 19583-19594/software.amazon.freertos.demo D/BluetoothGatt: onClientConnectionState() - status=19 clientIf=10 device=24:0A:C4:1D:78:AE

05-31 10:00:18.171 19583-19594/software.amazon.freertos.demo I/FRD: BLE connection state changed: 19; new state: BLE_DISCONNECTED

05-31 10:00:18.171 19583-19594/software.amazon.freertos.demo I/FRD: Disconnected from GATT server.

05-31 10:00:18.171 19583-19583/software.amazon.freertos.demo D/FRD: Bond state changed from 11 to 10

05-31 10:00:18.171 19583-19594/software.amazon.freertos.demo I/DeviceScanFragment: BLE connection status changed to: BLE_DISCONNECTED

05-31 10:00:18.171 19583-19583/software.amazon.freertos.demo I/DeviceScanFragment: connect switch isChecked: OFF
```
**Additional context**
N/A

**Comment by bxpan** [comment]
Hi rrivadeneira-rsc,

There's a problem in the bluetooth bonding that caused the connection to be closed. Could you check what is the bluetooth version on your phone? It needs to be 4.2 or higher. 

> 05-31 10:00:18.171 19583-19594/software.amazon.freertos.demo I/FRD: BLE connection state changed: 19; new state: BLE_DISCONNECTED

> 05-31 10:00:18.171 19583-19594/software.amazon.freertos.demo I/FRD: Disconnected from GATT server.

> 05-31 10:00:18.171 19583-19583/software.amazon.freertos.demo D/FRD: Bond state changed from 11 to 10

**Comment by rrivadeneira-rsc** [comment]
The Bluetooth version on the phone we were trying this with was 4.0 - so I see the problem. However, we tried on an iOS device I believe is with Bluetooth 4.0, with the iOS demo app, and we were able to connect without this error at the same level of security (the default "Numeric Comparison"). Is there a reason why Bluetooth versions between iOS and Android work differently? Is there something I'm missing? What is the specifics with suggesting Bluetooth 4.2 or higher?

Another question I had, if I change the device security to "Just Works" pairing, the Android phone on 4.0 will work. I did this by changing the following #define statements on `iot_ble_config_defaults.h`.
```
#define IOT_BLE_ENABLE_NUMERIC_COMPARISON ( 0 )
#define IOT_BLE_ENABLE_SECURE_CONNECTION ( 0 )
#define IOT_BLE_INPUT_OUTPUT ( eBTIONone )
```
So there are clearly pieces of security that are not be compatible with Android Bluetooth 4.0 and a 4.2 device. This might be a question for the firmware team, but am I able to try with other types of security as I did above? If so, how shall I get to them? Will that work? I want to understand why this features is not supporting phones that are just only 4-5 years old

Thanks for the response in advance.

**Comment by rrivadeneira-rsc** [comment]
Yes, I saw a numeric comparison number come up on iOS, and if I hit "pair" the device will pair successfully.

**Comment by bxpan** [comment]
> Yes, I saw a numeric comparison number come up on iOS, and if I hit "pair" the device will pair successfully.

What is the value you set for below when you were paring with iOS?

#define IOT_BLE_ENABLE_NUMERIC_COMPARISON  
#define IOT_BLE_ENABLE_SECURE_CONNECTION  
#define IOT_BLE_INPUT_OUTPUT  

We recommend using Bluetooth 4.2 because it provides enhanced security. With 4.0, the "Just works" pairing without numeric comparison works, but does not provide full secure connection, eg, man-in-the-middle attach could occur.

**Comment by rrivadeneira-rsc** [comment]
> What is the value you set for below when you were paring with iOS?

The values I set are the ones below:
```
#define IOT_BLE_ENABLE_NUMERIC_COMPARISON        ( 1 )
#define IOT_BLE_ENABLE_SECURE_CONNECTION         ( 1 )
#define IOT_BLE_INPUT_OUTPUT (eBTIODisplayYesNo)
```
So there is no way to make a secure connection with devices below Bluetooth 4.2? I thought "Passkey Entry/Display" pairing could be used for "legacy" bluetooth devices on this case.

**Comment by bxpan** [comment]
> #define IOT_BLE_ENABLE_NUMERIC_COMPARISON        ( 1 )
#define IOT_BLE_ENABLE_SECURE_CONNECTION         ( 1 )
#define IOT_BLE_INPUT_OUTPUT (eBTIODisplayYesNo)

These are the correct value to set to establish a secure connection. It requires minimum bluetooth 4.2 to work on Android. 

Which iOS device are you using?

**Comment by Qspace** [comment]
With BT 4.2, the pairing process was successfully but i still got a problem network connection.
![Screenshot_6](https://user-images.githubusercontent.com/13863220/66703112-4e0e7580-ed39-11e9-8a11-b6ff916997b9.png)

**Comment by pisukeman** [comment]
Hi!
We're not able to make the Just Works Pairing works.
Using the configuration:

#define IOT_BLE_ENABLE_NUMERIC_COMPARISON ( 0 )
#define IOT_BLE_ENABLE_SECURE_CONNECTION ( 0 )
#define IOT_BLE_INPUT_OUTPUT ( eBTIONone )

The app is not able to pair with the ESP32. The connectionStatus never gets BLE_CONNECTED value.

On the other hand if I try with other configurations, everything works fine. For example, we just tried the "Y" confirmation at ESP side and the pairing was good.
Any hints about what we are doing wrong?

Thanks in advance

**Comment by xuaninbox** [comment]
https://github.com/aws/amazon-freertos-ble-ios-sdk/issues/9#issuecomment-588579324

Seems to be related to the ESP stack

**Comment by abhidixi11** [comment]
I'm closing this issue, please feel free to open a new one.
