### ISSUE TITLE
[question] app changes

### ISSUE THREAD

**Issue by chegewara** [aws/amazon-freertos-ble-android-sdk#6]
Hi, 
i have one question about changes in app. In older version we were able to provide wifi credentials without login with cognito and i liked it, because i am using this app for developing purpose. Now i have to create cognito account just to provide wifi credentials even if i dont want to use mqtt over ble. Is that necessary?

Also i cant use old version because in afr release-1.5 all UUIDs got changed.

**Comment by bxpan** [comment]
Hi chegewara,

You may set this "mqtt" boolean to false to turn off the login screen, and you should be able to do wifi credentials just like before.

https://github.com/aws/amazon-freertos-ble-android-sdk/blob/beta/app/src/main/java/software/amazon/freertos/demo/DeviceScanFragment.java#L41

Yes, the UUIDs has been changed in release-1.5, so it is recommended to use the newer version.

**Comment by chegewara** [comment]
Thanks.
