### ISSUE TITLE
onClientConnectionState() - status=133 clientIf=7

### ISSUE THREAD

**Issue by ravirupareliya** [aws/amazon-freertos-ble-android-sdk#9]
Facing this error while connecting to ble in some android devices. Majorly it is in motorola, samsung and redmi. Specifically for OS 7.0 and 7.1.1

Other OS and device it is working perfect.

When I am trying to connect, it immediately calls `onClientConnectionStatus` with gatt error 133.

Any solution for this?

`
D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=7 device={deviceId}
I/AmazonFreeRTOSDevice: BLE connection state changed: 133; new state: BLE_DISCONNECTED
`

**Comment by bxpan** [comment]
The status error 133 means that the bluetooth connection is closed from the remote device it is trying to connect. 

What is the bluetooth version on the phones that have issue? Are they different than those phones that worked? 

Could you provide the full log from your phone as well as the full log from the device it is trying to connect to,  from the beginning of your app launched till the issue happened?

**Comment by ravirupareliya** [comment]
Bluetooth version of device is 4.2, It is moto e4.
I cannot find logs from device as I am not aware of it.
About phone log this is what I am getting, it is trying to connect few times but then suddenly it gives 133 error. 

Sometime it takes time to show 133 error and sometime it immediately throw 133 error

**Comment by bxpan** [comment]
Are you using the demo app or your own app? 

Do you see any of these logs? 
D/BluetoothGatt: connect() - device: 30:AE:A4:4A:FE:4A, auto: true
D/BluetoothGatt: onClientRegistered() - status=0 clientIf=8
D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=8 device=30:AE:A4:4A:FE:4A
I/FRD: Connected to GATT server.
I/FRD: Discovered Ble gatt services successfully. Bonding state: 12

**Comment by ravirupareliya** [comment]
Yes, it is there, even sometimes it gets connected also.
But those are rare cases, I mean it gets connected to device only once or twice out of 10 times.

**Comment by ravibhagavandas** [comment]
@ravirupareliya 
1. Which micro-controller device are you using on other end of the connection ? Could you also mention the Amazon FreeRTOS version running on the micro-controller device ?

2. By default the demo app and Amazon FreeRTOS is configured to run on highest security mode ( secure connection only with MITM protection). This means there is a pairing procedure with numeric comparison immediately after the GATT connection.  Are you getting any pairing notifications on the demo app?
For successful pairing, you have to also accept the numeric comparison code on device through a serial terminal. Please check `To discover and establish secure connections with your microcontroller over Bluetooth Low Energy` section in documentation [page](https://docs.aws.amazon.com/freertos/latest/userguide/ble-demo.html) for more details.

3. Could you collect device side logs by connecting to the serial terminal port of the micro-controller device. Depending on the micro-controller device you are using, you can get the details on this from board specific getting started guides [here](https://docs.aws.amazon.com/freertos/latest/userguide/getting-started-guides.html).

**Comment by abhidixi11** [comment]
I'm closing this issue, please feel free to open a new one.
